# Generated by Django 5.2.5 on 2025-08-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0002_country_my_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='my_user',
        ),
    ]
