# Generated by Django 5.2.5 on 2025-08-07 13:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=10, unique=True)),
                ('curr_symbol', models.CharField(max_length=10)),
                ('phone_code', models.CharField(max_length=10, unique=True)),
                ('my_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('my_user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('state_code', models.CharField(max_length=10, unique=True)),
                ('gst_code', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='locations.country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city_code', models.CharField(max_length=10)),
                ('phone_code', models.CharField(max_length=10, unique=True)),
                ('population', models.PositiveIntegerField()),
                ('avg_age', models.FloatField()),
                ('num_of_adult_males', models.PositiveIntegerField()),
                ('num_of_adult_females', models.PositiveIntegerField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='locations.state')),
            ],
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(fields=('country', 'name'), name='unique_state_name_per_country'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('state', 'name'), name='unique_city_name_per_state'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('state', 'city_code'), name='unique_city_code_per_state'),
        ),
    ]
