# Generated by Django 5.2.5 on 2025-08-08 07:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
