# Generated by Django 5.2.5 on 2025-08-08 09:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_country_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='state',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
